//! Cloud glyphs per provider: a node's `service` is the name of a drawio glyph of the chosen provider; group frame kinds.
use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Theme {
    Aws,
    Azure,
}

impl fmt::Display for Theme {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str(match self {
            Theme::Aws => "aws",
            Theme::Azure => "azure",
        })
    }
}

/// how a node is drawn
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Look {
    /// aws resource icon: stencil name (`mxgraph.aws4.<name>`), category colour
    AwsRes(&'static str, &'static str),
    /// aws standalone shape: stencil name, colour
    AwsShape(&'static str, &'static str),
    /// drawio's built-in azure2 icon: `<category>/<Name>` (`img/lib/azure2/<category>/<Name>.svg`)
    AzureImg(&'static str),
    /// a bordered text box
    Note,
}

/// every glyph drawio ships for the provider, generated by scripts/gen-glyphs.py:
/// aws `name<TAB>r|s<TAB>colour`, azure `<category>/<Name>`
const AWS_GLYPHS: &str = include_str!("glyphs/aws.tsv");
const AZURE_GLYPHS: &str = include_str!("glyphs/azure.txt");

/// where the full lists of names can be browsed
pub fn glyph_list_url(theme: Theme) -> &'static str {
    match theme {
        Theme::Aws => "https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/sidebar/Sidebar-AWS4.js",
        Theme::Azure => "https://github.com/jgraph/drawio/tree/dev/src/main/webapp/img/lib/azure2",
    }
}

/// names compare ignoring case, `-`, `_` and spaces (`route53` = `Route_53`)
fn norm(s: &str) -> String {
    s.chars().filter(|c| !matches!(c, '-' | '_' | ' ')).flat_map(char::to_lowercase).collect()
}

fn glyph_names(theme: Theme) -> Vec<&'static str> {
    match theme {
        Theme::Aws => AWS_GLYPHS.lines().filter_map(|l| l.split('\t').next()).collect(),
        Theme::Azure => AZURE_GLYPHS.lines().collect(),
    }
}

fn levenshtein(a: &str, b: &str) -> usize {
    let b: Vec<char> = b.chars().collect();
    let last = a.chars().fold((0..=b.len()).collect::<Vec<_>>(), |prev, ca| {
        let first = prev[0] + 1;
        b.iter().enumerate().fold(vec![first], |mut row, (j, cb)| {
            let v = (prev[j] + usize::from(ca != *cb)).min(prev[j + 1] + 1).min(row[j] + 1);
            row.push(v);
            row
        })
    });
    last[b.len()]
}

/// up to five names that look like what was meant
pub fn suggest(theme: Theme, name: &str) -> Vec<&'static str> {
    let q = norm(name);
    let mut scored: Vec<(usize, &'static str)> = glyph_names(theme)
        .into_iter()
        .filter_map(|g| {
            let n = norm(g.rsplit('/').next().unwrap_or(g));
            let d = levenshtein(&q, &n);
            (n.contains(&q) || q.contains(&n) || d <= 2).then_some((if n.contains(&q) { 0 } else { d }, g))
        })
        .collect();
    scored.sort();
    scored.into_iter().map(|(_, g)| g).take(5).collect()
}

/// the look of the glyph `name` in the theme (`note` is a text box in both); unknown or ambiguous names are errors
pub fn resolve(theme: Theme, name: &str) -> Result<Look, String> {
    let q = norm(name);
    if q == "note" {
        return Ok(Look::Note);
    }
    let unknown = || {
        let hint = suggest(theme, name);
        let hint = if hint.is_empty() { String::new() } else { format!(", did you mean: {}", hint.join(", ")) };
        format!("unknown {theme} glyph \"{name}\"{hint} (all names: {})", glyph_list_url(theme))
    };
    match theme {
        Theme::Aws => AWS_GLYPHS
            .lines()
            .filter_map(|l| {
                let mut f = l.split('\t');
                Some((f.next()?, f.next()?, f.next()?))
            })
            .find(|(n, _, _)| norm(n) == q)
            .map(|(n, kind, color)| if kind == "r" { Look::AwsRes(n, color) } else { Look::AwsShape(n, color) })
            .ok_or_else(unknown),
        Theme::Azure => {
            // `<category>/<Name>`, or a bare `<Name>` when only one category has it
            let last = |g: &str| norm(g.rsplit('/').next().unwrap_or(g));
            let hits: Vec<&'static str> = AZURE_GLYPHS.lines().filter(|g| if q.contains('/') { norm(g) == q } else { last(g) == q }).collect();
            match hits.as_slice() {
                [g] => Ok(Look::AzureImg(g)),
                [] => Err(unknown()),
                _ => Err(format!("ambiguous azure glyph \"{name}\", write one of: {}", hits.join(", "))),
            }
        }
    }
}

/// glyphs worth knowing for the theme: (name, what it is used for); `--agentic-help` lists them
pub fn common(theme: Theme) -> &'static [(&'static str, &'static str)] {
    match theme {
        Theme::Aws => &[
            ("client", "the human or browser that starts the story; usually the `start` node"),
            ("traditional_server", "a server outside the cloud account, e.g. a third-party SMTP host"),
            ("cloudfront", "CDN in front of the origins; routes paths to buckets or compute"),
            ("route_53", "DNS zone that points a domain at a service"),
            ("s3", "bucket for sites, uploads and data"),
            ("ec2", "virtual machine running your own software"),
            ("lambda", "serverless function"),
            ("fargate", "serverless containers"),
            ("elastic_beanstalk", "managed platform that runs your app on EC2"),
            ("api_gateway", "managed HTTP API front door for functions or backends"),
            ("dynamodb", "key-value / document database"),
            ("rds", "relational database"),
            ("sqs", "message queue"),
            ("sns", "publish/subscribe topic that fans alarms or events out"),
            ("ecr", "container image registry"),
            ("role", "IAM role that grants a workload access to other services"),
            ("parameter_store", "configuration and secrets store (SSM)"),
            ("cloudwatch_2", "metrics, logs and alarms"),
        ],
        Theme::Azure => &[
            ("general/Browser", "the human or browser that starts the story; usually the `start` node"),
            ("compute/Virtual_Machine", "virtual machine running your own software"),
            ("compute/Function_Apps", "serverless function"),
            ("app_services/App_Services", "managed platform that runs your web app"),
            ("other/Container_App_Environments", "managed service that runs containers"),
            ("containers/Container_Registries", "container image registry"),
            ("containers/Kubernetes_Services", "managed Kubernetes"),
            ("networking/Front_Doors", "CDN / global entry point in front of the origins"),
            ("networking/DNS_Zones", "DNS zone that points a domain at a service"),
            ("networking/Load_Balancers", "load balancer"),
            ("app_services/API_Management_Services", "managed API front door"),
            ("storage/Storage_Accounts", "blob storage for sites, uploads and data"),
            ("databases/SQL_Database", "relational database"),
            ("databases/Azure_Cosmos_DB", "document database"),
            ("integration/Event_Grid_Topics", "publish/subscribe topic"),
            ("identity/Managed_Identities", "identity that grants a workload access to other services"),
            ("security/Key_Vaults", "secrets and keys store"),
            ("management_governance/Monitor", "metrics, logs and alarms"),
        ],
    }
}

/// how a group frame is drawn
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GroupLook {
    pub key: &'static str,
    pub aliases: &'static [&'static str],
    /// aws group icon (None: plain frame)
    pub aws_icon: Option<&'static str>,
    pub aws_color: &'static str,
    pub azure_color: &'static str,
}

pub const GROUPS: &[GroupLook] = &[
    GroupLook { key: "network", aliases: &["vpc", "vnet", "virtual-network"], aws_icon: Some("mxgraph.aws4.group_vpc2"), aws_color: "#8C4FFF", azure_color: "#0078D4" },
    GroupLook { key: "region", aliases: &[], aws_icon: Some("mxgraph.aws4.group_region"), aws_color: "#147EBA", azure_color: "#0078D4" },
    GroupLook { key: "cloud", aliases: &["aws-cloud", "azure"], aws_icon: Some("mxgraph.aws4.group_aws_cloud"), aws_color: "#232F3E", azure_color: "#0078D4" },
    GroupLook { key: "group", aliases: &["generic"], aws_icon: None, aws_color: "#7D8998", azure_color: "#7D8998" },
];

pub fn group_look(name: &str) -> Option<&'static GroupLook> {
    let n = name.to_lowercase();
    GROUPS.iter().find(|g| g.key == n || g.aliases.contains(&n.as_str()))
}
